### PR TITLE
feat: PRCE-compliant RegEx updates for GitHub Linguist

### PR DESCRIPTION
**Pull request by muenzpraeger**
This PR updates certain RegEx elements to be PCRE RegEx compliant (specifically: changing `-` to `_` in named capture group identifiers).

The change is in [this commit](https://github.com/forcedotcom/apex-tmLanguage/commit/2e43ac7ca55edfc734cf0832ae12e4ac3005b675).

This is needed so that we can get the tmLanguage definition into [GitHub's Linguist for language detection](https://github.com/github/linguist/pull/6198) and syntax highlighting.

The other changes outside of the above linked commit are either dependency updates or reformatting of files (b/c of changed Prettier behavior).

### CODE REVIEW

**Comment by randi274** [comment]
Hi @muenzpraeger - we're going through open contributions this week to review, and I've added this one to our list! The caveat on this one is our github actions still need to be configured for this repo, so it may take some extra time for us to get out and published. Is this working against any sort of time crunch we should be aware of?

**Comment by muenzpraeger** [comment]
No time crunch. Let me know if I can help out.

There will likely be a few more PRs in the next time, as I discovered a few others non-matches. But not this week, I guess. ;-)

**Comment by randi274** [comment]
Hey @muenzpraeger - good news! I was able to get our CI/CD back up and running for this repo last week, so we're one step closer to getting this in! I've got this change running against our automated builds with #57. For testing purposes, are you expecting any functionality changes from this PR, or is it mainly to support a compliance update to Github Linguist?

**Comment by muenzpraeger** [comment]
@randi274 No functional changes beyond what's listed in the initial PR comment.

You can eventually expect a few more PRs soon, as I discovered a few language discrepancies/missing keywords. But not today or tomorrow. ;-)

**Comment by randi274** [comment]
Hey @muenzpraeger we're coming back around to this one today - I left a few questions on the broader PR to see if you've got thoughts based on team review.

**Comment by randi274** [comment]
Thanks for your patience on this @muenzpraeger! We were finally able to come back to this post-TDX and this has now been published with #57.

**Comment by muenzpraeger** [comment]
Wooohooot! Thank you so much!

**Comment by dschach** [comment]
Thank you all for working on this. I'm trying to get [highlightjs-apex](https://github.com/highlightjs/highlightjs-apex) updated, and this file helps a lot in writing that highlighter (which works for html). 

If anyone has advice on tools to make the process easier, I'm all ears, but this is a VERY complex file and has some circular dependencies that work in this kind of file but not in highlight.js.

**Comment by muenzpraeger** [comment]
@dschach Use [Shiki](https://github.com/shikijs/shiki) - that's what I am aiming for (disclaimer: I'm a contributor there too). Utilizing and enhancing our language experiences across IDE'a and web.

**Pull request closed without merging**
